import { createContext, useContext } from 'react'

// All UI text lives here. Default is Filipino, with English where it's clearer for teachers.
const fil = {
  appName: 'Basa at Sulat',
  navClass: 'Klase',
  navCheck: 'Basa',
  navBooks: 'Sulat',
  navSettings: 'Settings',
  statusLocal: 'Nasa laptop na ito',
  statusNoInternet: 'Hindi kailangan ng internet',
  statusAligner: 'Aligner (MMS)',
  statusOllama: 'Ollama (group plans)',
  statusMic: 'Mikropono',
  statusMock: 'Sample data muna: hindi pa konektado ang engine',
  statusReady: 'Handa',
  statusDown: 'Hindi available',

  classTitle: 'Klase',
  classSubtitle: 'Grade 2 · sample na klase',
  classCheck: 'Basahin',
  classPractice: 'Sanay',
  classLastCheck: 'Huling check',
  classNeverChecked: 'Wala pang check',
  classNeedsPractice: 'Kailangan ng practice',

  pickPassage: 'Pumili ng babasahin',
  words: 'salita',
  recordTitle: 'Basahin nang malakas',
  recordHint: 'Pindutin ang Record (o Space) at basahin ang kuwento.',
  recordStart: 'Record',
  recordStop: 'Stop',
  recordPrivacy: 'Ang recording ay nananatili sa laptop na ito.',
  micBlocked: 'Hindi magamit ang mikropono.',
  micBlockedFixWin: 'Windows: Settings → Privacy & security → Microphone → payagan ang desktop apps.',
  micBlockedFixLinux: 'Linux: tingnan kung naka-mute o napili ang tamang mikropono sa sound settings.',
  stagePrep: 'Inihahanda ang audio',
  stageAlign: 'Itinutugma ang mga salita',
  stageScore: 'Sinusuri ang pagbasa',
  stageSlow: 'Sandali lang… mas matagal sa lumang laptop.',

  reviewTitle: 'Resulta',
  wcpmLabel: 'words correct per minute',
  needsCheck: (n: number) => (n === 1 ? '1 salita ang kailangang tingnan mo' : `${n} salita ang kailangang tingnan mo`),
  allClear: 'Walang kailangang tingnan',
  scoredIn: (s: string) => `Na-score sa ${s} s gamit ang CPU ng laptop na ito`,
  nothingLeaves: 'Walang lumalabas sa laptop na ito.',
  confirm: 'I-confirm',
  reRecord: 'Ulitin',
  savedToast: 'Na-save na! Na-delete ang audio ✓',
  startPractice: (name: string) => `Simulan ang practice ni ${name}`,
  labelMatched: 'tama',
  labelMisread: 'mali ang basa',
  labelSkipped: 'nilaktawan',
  fixAs: 'Markahan bilang',
  heard: 'Narinig',
  pause: 'hinto',

  hearIt: 'Pakinggan',
  sayIt: 'Sabihin',
  listening: 'Nakikinig…',
  tryAgain: 'Subukan ulit',
  gotIt: 'Tama!',
  rereadTitle: 'Basahin ulit ang pangungusap',
  next: 'Susunod',
  done: 'Ang galing mo!',
  doneSub: 'Tapos na ang practice. Ipagpatuloy mo lang!',
  backToClass: 'Bumalik sa Klase',
  holdToExit: 'Pindutin nang matagal para lumabas',

  booksTitle: 'Sulat',
  booksSoon: 'Dito gagawa ng read-along na libro: i-type ang kuwento, i-record ang pagbasa ng isang fluent speaker.',
  settingsTitle: 'Settings',
  language: 'Wika ng app',
  modelsTitle: 'Mga modelo (lahat ay tumatakbo sa laptop na ito)',
  comingSoon: 'Malapit na',
  sampleData: 'Sample data',
  mascotName: 'Taw',
  mascotLines: ['Kumusta, Guro!', 'Tara, magbasa tayo!', 'Kaya natin ito!', 'Ako si Taw!'],
  kidHello: (n: string) => `Kumusta, ${n}! Handa ka na?`,
  kidRetry: (n: string) => `Kaya mo 'yan, ${n}!`,
  kidListen: 'Nakikinig ako…',
  kidRight: (n: string) => `Ang galing mo, ${n}!`,
  kidDone: (n: string) => `Tapos na tayo, ${n}! Ang husay mo!`,
  combo: (n: number) => `${n} sunod-sunod!`,
  sound: 'Tunog',
  thinking: (n: string) => `Sandali lang, nag-iisip si ${n}…`,
  navProfile: 'Profile',
  back: 'Bumalik',
  statStars: 'Mga star na nakuha:',
  statStreak: 'Sunod-sunod na araw:',
  statTime: 'Oras ng pagbasa:',
  days: (n: number) => (n === 1 ? '1 araw' : `${n} araw`),
  hm: (min: number) => `${Math.floor(min / 60)} h ${min % 60} m`,
  trendTitle: 'Words correct per minute',
  trendDelta: (d: number) => (d >= 0 ? `+${d} mula sa unang check` : `${d} mula sa unang check`),
  trendEmpty: 'Wala pang check. Simulan sa Basahin!',
  practicingTitle: 'Mga salitang pinag-aaralan',
  practicingEmpty: 'Walang salitang kailangang i-practice.',
  startSanay: 'Simulan ang Sanay',
  categoriesTitle: 'Mga paksa',
  showAll: 'Ipakita lahat',
  pickStory: 'Pumili ng kuwento',
  cat: { bukid: 'Bukid', pamilya: 'Pamilya', hayop: 'Hayop', kalikasan: 'Kalikasan', paaralan: 'Paaralan' } as Record<string, string>,
  starsEarned: (n: number) => (n === 1 ? '1 star ang nakuha mo!' : `${n} star ang nakuha mo!`),
  creditsTitle: 'Mga larawan',
  creditsText: 'Lahat ng larawan, pati si Taw na tamaraw, ay orihinal na gawa ng team.',
  learnersCount: (n: number) => `${n} learner`,
  greeting: (h: number): string => (h < 12 ? 'Magandang umaga, Guro!' : h < 18 ? 'Magandang hapon, Guro!' : 'Magandang gabi, Guro!'),
  cheersRight: ['Galing!', 'Ang husay!', 'Tama!', 'Sige pa!'],
  cheersRetry: ["Kaya mo 'yan!", 'Isa pa!', 'Subukan ulit'],
  sumChecked: 'Na-check ngayong linggo',
  sumPractice: 'Kailangan ng practice',
  sumWcpm: 'Average na words/min',
  sumStars: 'Mga star ng klase',
  basaEyebrow: 'Sino ang babasa ngayon?',
  dueTitle: 'Kailangang i-check ngayong linggo',
  dueEmpty: 'Na-check na ang lahat ngayong linggo. Ang galing!',
  doneTitle: 'Na-check na ngayong linggo',
  recentTitle: 'Mga kamakailang check',
  tipTitle: 'Tip',
  tipText: 'Pindutin ang Space para magsimula o huminto sa pag-record.',
  wpm: 'w/min',
  today: 'Ngayon',
  booksSubtitle: 'Mga read-along na libro sa wika ng mga bata',
  newBook: 'Gumawa ng bagong libro',
  newBookHint: 'I-type ang kuwento, i-record ang pagbasa',
  hasRecording: 'May recording',
  noRecording: 'Wala pang recording',
  readBy: (n: string) => `Binasa ni ${n}`,
  play: 'I-play',
  pausePlayback: 'I-pause',
  restart: 'Ulitin',
  useInBasa: 'Gamitin sa Basahin',
  sampleTiming: 'Sample na timing: wala pang totoong audio',
  stepWrite: 'Isulat',
  stepRecord: 'I-record',
  stepPreview: 'Silipin',
  fieldTitle: 'Pamagat',
  fieldLanguage: 'Wika',
  fieldLanguageHint: 'hal. Filipino, Ilocano, Ifugao',
  fieldReader: 'Sino ang babasa?',
  fieldReaderHint: 'hal. Lola Ising, Ma\'am Rose',
  fieldStory: 'Kuwento',
  fieldCategory: 'Paksa',
  nextStep: 'Susunod',
  recordModel: 'I-record ang pagbasa ng kuwento',
  recordModelHint: 'Ang fluent speaker ang babasa. Basahin nang malinaw at hindi nagmamadali.',
  aligning: 'Itinutugma ang bawat salita sa recording…',
  saveBook: 'I-save ang libro',
  savedBook: 'Na-save ang libro ✓',
  reRecordBook: 'I-record ulit',
  previewHint: 'Pakinggan: dapat sabay ang highlight at ang boses.',
  secDisplay: 'Laki ng teksto',
  sizeNormal: 'Karaniwan',
  sizeLarge: 'Malaki',
  secPrivacy: 'Privacy at data',
  audioStored: (n: number, mb: number) => `${n} audio file · ${mb} MB`,
  dataFolder: 'Folder ng data',
  deleteAudio: 'I-delete ang lahat ng audio ng mga bata',
  deleteConfirm: 'Sigurado? Pindutin ulit para i-delete',
  deletedAudio: (n: number) => `Na-delete ang ${n} audio file ✓`,
  keepsBooks: 'Hindi kasama ang recording ng mga libro.',
  secClass: 'Klase',
  addLearner: 'Magdagdag ng learner',
  learnerNamePh: 'Pangalan (o initials)',
  add: 'Idagdag',
  rename: 'Palitan ang pangalan',
  save: 'I-save',
  cancel: 'Kanselahin',
  secAbout: 'Tungkol sa app',
  aboutOffline: 'Gumagana nang walang internet. Walang data na umaalis sa laptop na ito.',
  version: 'Bersyon'
}

export type Strings = typeof fil

const en: Strings = {
  ...fil,
  navClass: 'Class',
  navCheck: 'Check',
  navBooks: 'Books',
  statusLocal: 'On this device',
  statusNoInternet: 'Internet not needed',
  statusMic: 'Microphone',
  statusMock: 'Sample data: the engine is not connected yet',
  statusReady: 'Ready',
  statusDown: 'Unavailable',
  classTitle: 'Class',
  classSubtitle: 'Grade 2 · sample class',
  classCheck: 'Check',
  classPractice: 'Practice',
  classLastCheck: 'Last check',
  classNeverChecked: 'Not checked yet',
  classNeedsPractice: 'Needs practice',
  pickPassage: 'Choose a passage',
  words: 'words',
  recordTitle: 'Read aloud',
  recordHint: 'Press Record (or Space) and read the story.',
  recordPrivacy: 'The recording stays on this laptop.',
  micBlocked: "Can't use the microphone.",
  micBlockedFixWin: 'Windows: Settings → Privacy & security → Microphone → allow desktop apps.',
  micBlockedFixLinux: 'Linux: check the mic is not muted and is selected in sound settings.',
  stagePrep: 'Preparing audio',
  stageAlign: 'Lining up words',
  stageScore: 'Scoring the reading',
  stageSlow: 'Still working… older laptops take longer.',
  reviewTitle: 'Result',
  needsCheck: (n) => (n === 1 ? '1 word needs your check' : `${n} words need your check`),
  allClear: 'Nothing to check',
  scoredIn: (s) => `Scored in ${s} s on this laptop's CPU`,
  nothingLeaves: 'Nothing leaves this laptop.',
  confirm: 'Confirm',
  reRecord: 'Re-record',
  savedToast: 'Saved · audio deleted ✓',
  startPractice: (name) => `Start practice for ${name}`,
  labelMatched: 'correct',
  labelMisread: 'misread',
  labelSkipped: 'skipped',
  fixAs: 'Mark as',
  heard: 'Heard',
  pause: 'pause',
  hearIt: 'Hear it',
  sayIt: 'Say it',
  listening: 'Listening…',
  tryAgain: 'Try again',
  gotIt: 'Got it!',
  rereadTitle: 'Read the sentence again',
  next: 'Next',
  done: 'You did great!',
  doneSub: 'Practice finished. Keep it up!',
  backToClass: 'Back to Class',
  holdToExit: 'Hold to exit',
  booksTitle: 'Books',
  booksSoon: 'Make read-along books here: type a story, record a fluent speaker reading it.',
  language: 'App language',
  modelsTitle: 'Models (all run on this laptop)',
  comingSoon: 'Coming soon',
  sampleData: 'Sample data',
  thinking: (n) => `${n} is thinking…`,
  mascotLines: ['Hello, Teacher!', "Let's read!", 'We can do this!', "I'm Taw!"],
  kidHello: (n) => `Hi, ${n}! Ready?`,
  kidRetry: (n) => `You can do it, ${n}!`,
  kidListen: "I'm listening…",
  kidRight: (n) => `Great job, ${n}!`,
  kidDone: (n) => `We're done, ${n}! You did great!`,
  combo: (n) => `${n} in a row!`,
  sound: 'Sound',
  back: 'Back',
  statStars: 'Stars collected:',
  statStreak: 'Days read in a row:',
  statTime: 'Time spent reading:',
  days: (n) => (n === 1 ? '1 day' : `${n} days`),
  trendDelta: (d) => (d >= 0 ? `+${d} since the first check` : `${d} since the first check`),
  trendEmpty: 'No checks yet. Start with Check!',
  practicingTitle: 'Words being practiced',
  practicingEmpty: 'No words to practice.',
  startSanay: 'Start practice',
  categoriesTitle: 'Topics',
  showAll: 'Show all',
  pickStory: 'Choose a story',
  cat: { bukid: 'Farm', pamilya: 'Family', hayop: 'Animals', kalikasan: 'Nature', paaralan: 'School' },
  starsEarned: (n) => (n === 1 ? 'You earned 1 star!' : `You earned ${n} stars!`),
  creditsTitle: 'Illustrations',
  creditsText: 'All illustrations, including Taw the tamaraw, are original work by the team.',
  learnersCount: (n) => `${n} learners`,
  greeting: (h) => (h < 12 ? 'Good morning, Teacher!' : h < 18 ? 'Good afternoon, Teacher!' : 'Good evening, Teacher!'),
  cheersRight: ['Great job!', 'Awesome!', 'Correct!', 'Keep going!'],
  cheersRetry: ['You can do it!', 'One more time!', 'Try again'],
  sumChecked: 'Checked this week',
  sumPractice: 'Need practice',
  sumWcpm: 'Average words/min',
  sumStars: 'Class stars',
  basaEyebrow: 'Who reads today?',
  dueTitle: 'Due for a check this week',
  dueEmpty: 'Everyone has been checked this week. Great job!',
  doneTitle: 'Checked this week',
  recentTitle: 'Recent checks',
  tipText: 'Press Space to start or stop recording.',
  today: 'Today',
  booksSubtitle: "Read-along books in the children's language",
  newBook: 'Make a new book',
  newBookHint: 'Type the story, record the reading',
  hasRecording: 'Has recording',
  noRecording: 'No recording yet',
  readBy: (n) => `Read by ${n}`,
  play: 'Play',
  pausePlayback: 'Pause',
  restart: 'Restart',
  useInBasa: 'Use in a check',
  sampleTiming: 'Sample timing: no real audio yet',
  stepWrite: 'Write',
  stepRecord: 'Record',
  stepPreview: 'Preview',
  fieldTitle: 'Title',
  fieldLanguage: 'Language',
  fieldLanguageHint: 'e.g. Filipino, Ilocano, Ifugao',
  fieldReader: 'Who is reading?',
  fieldReaderHint: "e.g. Lola Ising, Ma'am Rose",
  fieldStory: 'Story',
  fieldCategory: 'Topic',
  nextStep: 'Next',
  recordModel: 'Record the story being read',
  recordModelHint: 'The fluent speaker reads it. Read clearly and not too fast.',
  aligning: 'Lining up every word with the recording…',
  saveBook: 'Save book',
  savedBook: 'Book saved ✓',
  reRecordBook: 'Record again',
  previewHint: 'Listen: the highlight should follow the voice.',
  secDisplay: 'Text size',
  sizeNormal: 'Normal',
  sizeLarge: 'Large',
  secPrivacy: 'Privacy & data',
  audioStored: (n, mb) => `${n} audio files · ${mb} MB`,
  dataFolder: 'Data folder',
  deleteAudio: "Delete all children's audio",
  deleteConfirm: 'Sure? Press again to delete',
  deletedAudio: (n) => `Deleted ${n} audio files ✓`,
  keepsBooks: 'Book recordings are kept.',
  secClass: 'Class',
  addLearner: 'Add a learner',
  learnerNamePh: 'Name (or initials)',
  add: 'Add',
  rename: 'Rename',
  save: 'Save',
  cancel: 'Cancel',
  secAbout: 'About',
  aboutOffline: 'Works without internet. No data leaves this laptop.',
  version: 'Version'
}

export const STRINGS = { fil, en }
export type Lang = keyof typeof STRINGS

export const LangContext = createContext<{ lang: Lang; setLang: (l: Lang) => void }>({
  lang: 'fil',
  setLang: () => {}
})

export function useT(): Strings {
  return STRINGS[useContext(LangContext).lang]
}
