import { createContext, useContext } from 'react'

// All UI text lives here. Default is Filipino, with English where it's clearer for teachers.
const fil = {
  appName: 'Basa at Sulat',
  navClass: 'Klase',
  navCheck: 'Basa',
  navBooks: 'Sulat',
  navSettings: 'Settings',
  statusLocal: 'Nasa laptop na ito',
  statusNoInternet: 'Hindi kailangan ng internet',
  statusAligner: 'Aligner (MMS)',
  statusOllama: 'Ollama (group plans)',
  statusMic: 'Mikropono',
  statusMock: 'Sample data muna: hindi pa konektado ang engine',
  statusReady: 'Handa',
  statusDown: 'Hindi available',

  classTitle: 'Klase',
  classSubtitle: 'Grade 2 · sample na klase',
  classCheck: 'Basahin',
  classPractice: 'Sanay',
  classLastCheck: 'Huling check',
  classNeverChecked: 'Wala pang check',
  classNeedsPractice: 'Kailangan ng practice',

  pickPassage: 'Pumili ng babasahin',
  words: 'salita',
  recordTitle: 'Basahin nang malakas',
  recordHint: 'Pindutin ang Record (o Space) at basahin ang kuwento.',
  recordStart: 'Record',
  recordStop: 'Stop',
  recordPrivacy: 'Ang recording ay nananatili sa laptop na ito.',
  micBlocked: 'Hindi magamit ang mikropono.',
  micBlockedFixWin: 'Windows: Settings → Privacy & security → Microphone → payagan ang desktop apps.',
  micBlockedFixLinux: 'Linux: tingnan kung naka-mute o napili ang tamang mikropono sa sound settings.',
  stagePrep: 'Inihahanda ang audio',
  stageAlign: 'Itinutugma ang mga salita',
  stageScore: 'Sinusuri ang pagbasa',
  stageSlow: 'Sandali lang… mas matagal sa lumang laptop.',

  reviewTitle: 'Resulta',
  wcpmLabel: 'words correct per minute',
  needsCheck: (n: number) => (n === 1 ? '1 salita ang kailangang tingnan mo' : `${n} salita ang kailangang tingnan mo`),
  allClear: 'Walang kailangang tingnan',
  scoredIn: (s: string) => `Na-score sa ${s} s gamit ang CPU ng laptop na ito`,
  nothingLeaves: 'Walang lumalabas sa laptop na ito.',
  confirm: 'I-confirm',
  reRecord: 'Ulitin',
  savedToast: 'Na-save · na-delete ang audio ✓',
  startPractice: (name: string) => `Simulan ang practice ni ${name}`,
  labelMatched: 'tama',
  labelMisread: 'mali ang basa',
  labelSkipped: 'nilaktawan',
  fixAs: 'Markahan bilang',
  heard: 'Narinig',
  pause: 'hinto',

  hearIt: 'Pakinggan',
  sayIt: 'Sabihin',
  listening: 'Nakikinig…',
  tryAgain: 'Subukan ulit',
  gotIt: 'Tama!',
  rereadTitle: 'Basahin ulit ang pangungusap',
  next: 'Susunod',
  done: 'Ang galing!',
  doneSub: 'Tapos na ang practice.',
  backToClass: 'Bumalik sa Klase',
  holdToExit: 'Pindutin nang matagal para lumabas',

  booksTitle: 'Sulat',
  booksSoon: 'Dito gagawa ng read-along na libro: i-type ang kuwento, i-record ang pagbasa ng isang fluent speaker.',
  settingsTitle: 'Settings',
  language: 'Wika ng app',
  modelsTitle: 'Mga modelo (lahat ay tumatakbo sa laptop na ito)',
  comingSoon: 'Malapit na',
  sampleData: 'Sample data',
  mascotName: 'Taw',
  thinking: (n: string) => `Nag-iisip si ${n}…`,
  navProfile: 'Profile',
  back: 'Bumalik',
  statStars: 'Mga star na nakuha:',
  statStreak: 'Sunod-sunod na araw:',
  statTime: 'Oras ng pagbasa:',
  days: (n: number) => (n === 1 ? '1 araw' : `${n} araw`),
  hm: (min: number) => `${Math.floor(min / 60)} h ${min % 60} m`,
  trendTitle: 'Words correct per minute',
  trendDelta: (d: number) => (d >= 0 ? `+${d} mula sa unang check` : `${d} mula sa unang check`),
  trendEmpty: 'Wala pang check. Simulan sa Basahin!',
  practicingTitle: 'Mga salitang pinag-aaralan',
  practicingEmpty: 'Walang salitang kailangang i-practice.',
  startSanay: 'Simulan ang Sanay',
  categoriesTitle: 'Mga paksa',
  showAll: 'Ipakita lahat',
  pickStory: 'Pumili ng kuwento',
  cat: { bukid: 'Bukid', pamilya: 'Pamilya', hayop: 'Hayop', kalikasan: 'Kalikasan', paaralan: 'Paaralan' } as Record<string, string>,
  starsEarned: (n: number) => (n === 1 ? '1 star ang nakuha mo!' : `${n} star ang nakuha mo!`),
  creditsTitle: 'Mga larawan',
  creditsText: 'Microsoft Fluent Emoji (MIT License). Ang tamaraw ay orihinal na gawa ng team.',
  learnersCount: (n: number) => `${n} learner`
}

export type Strings = typeof fil

const en: Strings = {
  ...fil,
  navClass: 'Class',
  navCheck: 'Check',
  navBooks: 'Books',
  statusLocal: 'On this device',
  statusNoInternet: 'Internet not needed',
  statusMic: 'Microphone',
  statusMock: 'Sample data: the engine is not connected yet',
  statusReady: 'Ready',
  statusDown: 'Unavailable',
  classTitle: 'Class',
  classSubtitle: 'Grade 2 · sample class',
  classCheck: 'Check',
  classPractice: 'Practice',
  classLastCheck: 'Last check',
  classNeverChecked: 'Not checked yet',
  classNeedsPractice: 'Needs practice',
  pickPassage: 'Choose a passage',
  words: 'words',
  recordTitle: 'Read aloud',
  recordHint: 'Press Record (or Space) and read the story.',
  recordPrivacy: 'The recording stays on this laptop.',
  micBlocked: "Can't use the microphone.",
  micBlockedFixWin: 'Windows: Settings → Privacy & security → Microphone → allow desktop apps.',
  micBlockedFixLinux: 'Linux: check the mic is not muted and is selected in sound settings.',
  stagePrep: 'Preparing audio',
  stageAlign: 'Lining up words',
  stageScore: 'Scoring the reading',
  stageSlow: 'Still working… older laptops take longer.',
  reviewTitle: 'Result',
  needsCheck: (n) => (n === 1 ? '1 word needs your check' : `${n} words need your check`),
  allClear: 'Nothing to check',
  scoredIn: (s) => `Scored in ${s} s on this laptop's CPU`,
  nothingLeaves: 'Nothing leaves this laptop.',
  confirm: 'Confirm',
  reRecord: 'Re-record',
  savedToast: 'Saved · audio deleted ✓',
  startPractice: (name) => `Start practice for ${name}`,
  labelMatched: 'correct',
  labelMisread: 'misread',
  labelSkipped: 'skipped',
  fixAs: 'Mark as',
  heard: 'Heard',
  pause: 'pause',
  hearIt: 'Hear it',
  sayIt: 'Say it',
  listening: 'Listening…',
  tryAgain: 'Try again',
  gotIt: 'Got it!',
  rereadTitle: 'Read the sentence again',
  next: 'Next',
  done: 'Great job!',
  doneSub: 'Practice finished.',
  backToClass: 'Back to Class',
  holdToExit: 'Hold to exit',
  booksTitle: 'Books',
  booksSoon: 'Make read-along books here: type a story, record a fluent speaker reading it.',
  language: 'App language',
  modelsTitle: 'Models (all run on this laptop)',
  comingSoon: 'Coming soon',
  sampleData: 'Sample data',
  thinking: (n) => `${n} is thinking…`,
  back: 'Back',
  statStars: 'Stars collected:',
  statStreak: 'Days read in a row:',
  statTime: 'Time spent reading:',
  days: (n) => (n === 1 ? '1 day' : `${n} days`),
  trendDelta: (d) => (d >= 0 ? `+${d} since the first check` : `${d} since the first check`),
  trendEmpty: 'No checks yet. Start with Check!',
  practicingTitle: 'Words being practiced',
  practicingEmpty: 'No words to practice.',
  startSanay: 'Start practice',
  categoriesTitle: 'Topics',
  showAll: 'Show all',
  pickStory: 'Choose a story',
  cat: { bukid: 'Farm', pamilya: 'Family', hayop: 'Animals', kalikasan: 'Nature', paaralan: 'School' },
  starsEarned: (n) => (n === 1 ? 'You earned 1 star!' : `You earned ${n} stars!`),
  creditsTitle: 'Illustrations',
  creditsText: 'Microsoft Fluent Emoji (MIT License). The tamaraw mascot is original work by the team.',
  learnersCount: (n) => `${n} learners`
}

export const STRINGS = { fil, en }
export type Lang = keyof typeof STRINGS

export const LangContext = createContext<{ lang: Lang; setLang: (l: Lang) => void }>({
  lang: 'fil',
  setLang: () => {}
})

export function useT(): Strings {
  return STRINGS[useContext(LangContext).lang]
}
